---
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

# MD013/line-length
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
MD013:
  line_length: 120
  code_blocks: false  # disable checking code blocks
  tables: false       # disable checking tables

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
MD033: false   # Allow inline HTML

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md046.md
MD046: false   # Allow indented code block
...
