# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
---

# Project information
site_name: 'dreknix - Documentation'
# site_description: 'dreknix'
site_author: 'dreknix'
site_url: !ENV [MKDOCS_SITE_URL, 'http://localhost:8000']
dev_addr: !ENV [MKDOCS_DEV_ADDR, '127.0.0.1:8000']

# Repository
repo_url: 'https://github.com/dreknix/wiki'
repo_name: 'dreknix/wiki'
edit_uri: 'edit/main/docs/'

use_directory_urls: false

validation:
  absolute_links: warn
  unrecognized_links: warn
  nav:
    omitted_files: ignore
    absolute_links: warn

# Configuration
theme:
  name: 'material'
  language: 'en'
  favicon: /assets/images/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'teal'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'teal'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    # - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following
    - toc.follow
    # # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration
    # # - toc.integrate
  icon:
    logo: material/library
    # repo: fontawesome/brands/bitbucket
    #
    # search for icons: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    tag:
      ansible: simple/ansible
      bash: simple/gnubash
      debian: simple/debian
      docker: simple/docker
      git: simple/git
      github: simple/github
      gitlab: simple/gitlab
      homeassistant: simple/homeassistant
      html: fontawesome/brands/html5
      json: material/code-json
      markdown: simple/markdown
      neovim: simple/neovim
      powershell: simple/powershell
      proxmox: simple/proxmox
      python: simple/python
      tmux: simple/tmux
      truenas: simple/truenas
      ubuntu: simple/ubuntu
      vim: simple/vim
      windows: material/microsoft-windows
      yaml: simple/yaml

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  tags:
    Ansible: ansible
    bash: bash
    Debian: debian
    Docker: docker
    Git: git
    GitHub: github
    GitLab: gitlab
    HomeAssistant: homeassistant
    HTML: html
    JSON: json
    Markdown: markdown
    Neovim: neovim
    PowerShell: powershell
    Proxmox: proxmox
    Python: python
    tmux: tmux
    TrueNAS: truenas
    Ubuntu: ubuntu
    Vim: vim
    Windows: windows
    YAML: yaml

copyright: >
  Copyright &copy; 2022-2023 dreknix –
  <a href="#__consent">Change cookie settings</a>

# Plugins
plugins:
  - awesome-pages:
      # collapse_single_pages: true
      strict: true
  - blog:
      enabled: true
      post_readtime: false
  - git-committers:
      enabled: true
      repository: dreknix/wiki
      branch: main
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  # - privacy:
  #     enabled: true
  #     concurrency: 1
  #     cache: false
  - search:
      enabled: true
      lang: en
  - rss:
      enabled: true
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      pretty_print: true
      categories:
        - categories
  - tags:
      enabled: true
      tags_file: tags.md

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  # https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.keys
  # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: snippets/
      # auto_append: abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        # see: https://squidfunk.github.io/mkdocs-material/reference/diagrams/
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "&#128279;"
      toc_depth: 5

...
