---

# https://taskfile.dev
version: '3'

tasks:

  lint:
    desc: Lint YAML files
    cmds:
      - yamllint .

  serve:
    desc: Start local wiki page
    cmds:
      - mkdocs serve

  update:
    desc: Update all Python packages including Mkdocs Material
    cmds:
      # Upgrade pip3, setuptools and install wheel
      - pip3 install --require-virtualenv --upgrade pip setuptools wheel
      # Install/upgrade requirements
      - pip3 install --require-virtualenv --upgrade -r requirements.txt

...
