---

# https://taskfile.dev
version: '3'

tasks:

  update:
    desc: Update all Python packages including Mkdocs Material
    cmds:
      - pip3 install --upgrade -r requirements.txt

  serve:
    desc: Start local wiki page
    cmds:
      - mkdocs serve

...
