---

# https://taskfile.dev
version: '3'

tasks:

  python:
    desc: Update all Python packages including Mkdocs Material
    cmds:
      # Upgrade pip3, setuptools and install wheel
      - pip3 install --upgrade pip setuptools wheel
      # Install/upgrade requirements
      - pip3 install --upgrade -r requirements.txt

  serve:
    desc: Start local wiki page
    cmds:
      - mkdocs serve

...
